Repository awell-health/sol-scheduling, pull requests merged in 2024-10, with the labels that each got.

#33 ui tests
  chromatic.config.json
  package.json
  src/atoms/Calendar/week/WeekCalendar.spec.ts
  src/atoms/Calendar/week/WeekCalendar.stories.tsx
  src/atoms/ProviderAvatar/ProviderAvatar.tsx
  src/atoms/ProviderSelection/ProviderFilter/FilterBadge.tsx
  src/atoms/ProviderSelection/ProviderFilter/FilterOverlayHeader.tsx
  src/atoms/ProviderSelection/ProviderSelection.spec.ts
  src/atoms/ProviderSelection/ProviderSelection.stories.tsx
  src/molecules/Scheduler/Scheduler.stories.tsx
  style.css
Labels: enhancement, Tests, Review effort [1-5]: 3

#34 Add error handling when fetching providers fail
  package.json
  src/PreferencesProvider/PreferencesContext.tsx
  src/SolApiProvider/SolApiContext.tsx
  src/atoms/FetchingProvidersError/FetchingProvidersError.stories.tsx
  src/atoms/FetchingProvidersError/FetchingProvidersError.tsx
  src/atoms/FetchingProvidersError/index.tsx
  src/atoms/ProviderSelection/ProviderSelection.tsx
  src/atoms/index.tsx
Labels: enhancement, Review effort [1-5]: 3, error handling, bug fix

#35 fix layout
  package.json
  src/atoms/ProviderSelection/ProviderSelection.tsx
Labels: enhancement, Review effort [1-5]: 2, miscellaneous

#36 ET-278-fix-location-filter
  package.json
  src/PreferencesProvider/utils.ts
  src/lib/api/schema/GetProviders.schema.ts
Labels: enhancement, Review effort [1-5]: 2, bug fix

#38 Et 277 fix infinity loading screen
  package.json
  src/atoms/ProviderSelection/ProviderSelection.tsx
Labels: enhancement, Review effort [1-5]: 2, bug fix

#39 Filter UI
  package.json
  src/atoms/Calendar/week/WeekCalendar.tsx
  src/atoms/ProviderSelection/ProviderFilter/FilterBadge.tsx
  src/atoms/ProviderSelection/ProviderFilter/FilterOverlayBadge.tsx
  src/atoms/ProviderSelection/ProviderFilter/FilterOverlayContainer.tsx
  src/atoms/ProviderSelection/ProviderFilter/ProviderFilter.tsx
  src/atoms/ProviderSelection/types.ts
  src/lib/utils/location/locationUtils.test.ts
  src/lib/utils/location/locationUtils.ts
  style.css
Labels: enhancement, Review effort [1-5]: 3, bug fix

#40 cosmetic changes to filters
  package.json
  src/atoms/ProviderSelection/ProviderCard.tsx
  src/atoms/ProviderSelection/ProviderFilter/utils.ts
  style.css
Labels: enhancement, Review effort [1-5]: 2, bug fix

#42 update location to In-Person or Telehealth
  package.json
  src/atoms/BookingError/BookingError.stories.tsx
  src/atoms/Calendar/week/WeekCalendar.stories.tsx
  src/atoms/Slots/Slots.stories.tsx
  src/hostedPages/SchedulingActivity.stories.tsx
  src/lib/api/__mocks__/GetProviderAvailability.mock.ts
  src/lib/api/__mocks__/GetProviders.mock.ts
  src/lib/api/schema/atoms/EventDeliveryMethod.schema.ts
  src/lib/api/schema/shared.schema.ts
  src/lib/utils/availabilities/filters.test.ts
  src/lib/utils/availabilities/filters.ts
  src/lib/utils/preferences/preparePreferencesForSalesforce.test.ts
  src/molecules/Scheduler/Scheduler.stories.tsx
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#43 fix(modality): support additional modalities
  package.json
  src/atoms/BookingError/BookingError.stories.tsx
  src/atoms/Calendar/week/WeekCalendar.spec.ts
  src/atoms/ProviderSelection/ProviderSelection.spec.ts
  src/lib/api/schema/atoms/TherapeuticModality.schema.ts
  src/molecules/Scheduler/Scheduler.spec.ts
Labels: enhancement, Review effort [1-5]: 2, bug fix

#44 fix(interaction-tests): passing storybook tests
  .github/workflows/storybook-interaction-tests.yml
  src/atoms/Calendar/week/WeekCalendar.spec.ts
  src/atoms/Calendar/week/WeekCalendar.stories.tsx
  src/lib/api/schema/atoms/TherapeuticModality.schema.ts
  src/molecules/Scheduler/Scheduler.spec.ts
Labels: enhancement, Tests, Review effort [1-5]: 3

#46 allow empty strings
  package.json
  src/lib/api/schema/atoms/LocationFacility.schema.ts
  src/lib/api/schema/atoms/LocationState.schema.ts
Labels: enhancement, Review effort [1-5]: 2, bug fix

#47 allow user to re-render providers if error dissappears
  package.json
  src/SolApiProvider/SolApiContext.tsx
Labels: enhancement, Review effort [1-5]: 2, bug fix

#48 fix delivery method filter
  package.json
  src/PreferencesProvider/utils.ts
  src/atoms/ProviderSelection/ProviderSelection.tsx
Labels: enhancement, Review effort [1-5]: 2, bug fix

#50 Tp 2578 ux updates
  package.json
  src/atoms/Calendar/week/WeekCalendar.tsx
  src/atoms/FetchingProvidersError/FetchingProvidersError.tsx
Labels: enhancement, Review effort [1-5]: 3, bug fix

#52 ET-304-sort-filter
  package.json
  src/atoms/ProviderSelection/ProviderFilter/FilterList.tsx
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#53 update-location-label
  package.json
  src/PreferencesProvider/utils.ts
  src/lib/api/schema/atoms/ClinicalFocus.schema.ts
Labels: enhancement, other, Review effort [1-5]: 1

#54 ET-318: add age validation to API schema
  package.json
  src/atoms/Errors/BookingError/BookingError.stories.tsx
  src/atoms/Errors/BookingError/BookingError.tsx
  src/atoms/Errors/BookingError/index.tsx
  src/atoms/Errors/FetchingProvidersError/FetchingProvidersError.stories.tsx
  src/atoms/Errors/FetchingProvidersError/FetchingProvidersError.tsx
  src/atoms/Errors/FetchingProvidersError/index.tsx
  src/atoms/Errors/index.ts
  src/atoms/ProviderSelection/ProviderSelection.tsx
  src/atoms/index.tsx
  src/lib/api/schema/__tests__/GetProviders.schema.test.ts
  src/lib/api/schema/atoms/Age.schema.ts
  src/lib/utils/preferences/preparePreferencesForSalesforce.test.ts
Labels: Review effort [1-5]: 3

#56 remove upper limit on age
  package.json
  src/lib/api/schema/__tests__/GetProviders.schema.test.ts
  src/lib/api/schema/atoms/Age.schema.ts
Labels: Review effort [1-5]: 2

#58 chore(docs): update age validation
  docs/api.spec.yaml
Labels: Review effort [1-5]: 1

#59 Support retrieving a provider by Wordpress ID
  docs/api.spec.yaml
  package.json
  src/lib/api/__mocks__/GetProvider.mock.ts
  src/lib/api/schema/GetProvider.schema.ts
Labels: Review effort [1-5]: 2
