Repository awell-health/sol-scheduling, pull requests merged in 2024-11, with the labels that each got.

#65 chore(docs): new prod URL
  docs/api.spec.yaml
Labels: Review effort [1-5]: 1

#63 fix-facility-label
  package.json
  src/atoms/Calendar/week/WeekCalendar.tsx
Labels: Review effort [1-5]: 2

#66 update-api-docs
  docs/api.spec.yaml
  src/molecules/Scheduler/Scheduler.spec.ts
Labels: Review effort [1-5]: 1

#67 chore(): minor improvements
  package.json
  src/SolApiProvider/SolApiContext.tsx
  src/hostedPages/SchedulingActivity.stories.tsx
  src/hostedPages/SchedulingActivityWithoutProviderSelection.stories.tsx
  src/lib/api/__mocks__/GetProviderAvailability.mock.ts
  src/molecules/Scheduler/__mocks__/scheduler.mocks.ts
Labels: Review effort [1-5]: 3

#68 feat(): autofocus on week with availability
  src/atoms/Calendar/week/WeekCalendar.spec.ts
  src/atoms/Calendar/week/WeekCalendar.stories.tsx
  src/atoms/Calendar/week/WeekCalendar.tsx
  src/molecules/Scheduler/Scheduler.stories.tsx
Labels: Review effort [1-5]: 3

#69 ET-418: hide profile link
  src/atoms/ProviderSelection/ProviderCard.tsx
Labels: Review effort [1-5]: 2

#70 ET-421: Weekcalendar - disable going to the past
  src/atoms/Calendar/week/WeekCalendar.spec.ts
  src/atoms/Calendar/week/WeekCalendar.tsx
Labels: Review effort [1-5]: 2

#71 ET-420: Weekcalendar - set location based on preference
  src/atoms/Calendar/week/WeekCalendar.spec.ts
  src/atoms/Calendar/week/WeekCalendar.stories.tsx
  src/atoms/Calendar/week/WeekCalendar.tsx
  src/molecules/Scheduler/Scheduler.tsx
Labels: Review effort [1-5]: 3

#72 ET-419: increase avatar size
  src/atoms/ProviderSelection/ProviderCard.tsx
  src/molecules/Scheduler/Scheduler.tsx
Labels: Review effort [1-5]: 2

#73 update-avatar-size
  package.json
  src/atoms/ProviderSelection/ProviderCard.tsx
  src/molecules/Scheduler/Scheduler.tsx
Labels: Review effort [1-5]: 2

#74 Et 424 show all filters on small screen
  package.json
  src/atoms/ProviderSelection/ProviderFilter/FilterBadge.tsx
  src/atoms/ProviderSelection/ProviderFilter/ProviderFilter.tsx
Labels: Review effort [1-5]: 2

#75 Et 454 show next available slots
  package.json
  src/atoms/AvailabilitySlots/AvailabilitySlot.stories.tsx
  src/atoms/AvailabilitySlots/AvailabilitySlot.tsx
  src/atoms/AvailabilitySlots/AvailabilitySlots.stories.tsx
  src/atoms/AvailabilitySlots/AvailabilitySlots.tsx
  src/atoms/AvailabilitySlots/index.tsx
  src/atoms/Calendar/week/WeekCalendar.tsx
  src/atoms/ProviderSelection/ProviderCard.tsx
  src/atoms/index.tsx
  src/molecules/Scheduler/Scheduler.spec.ts
  src/molecules/Scheduler/Scheduler.tsx
Labels: Review effort [1-5]: 3
